Make FASTLY_DEBUG_MODE display errors. (#704)
When FASTLY_DEBUG_MODE is set to 'true', error responses should be
displayed, not suppressed (displayed as an empty response).

Example output when FASTLY_DEBUG_MODE is set during `make testacc` in
the Fastly Terraform provider:
```
http.Request (dump): "POST /ngwaf/v1/workspaces HTTP/1.1\r\nHost: api.fastly.com\r\nUser-Agent: Terraform/1.12.2 (+https://www.terraform.io) Terraform-Plugin-SDK/2.37.0 terraform-provider-fastly/acc\r\nContent-Length: 298\r\nAccept: application/json\r\nContent-Type: application/json\r\nAccept-Encoding: gzip\r\n\r\n{\"attack_signal_thresholds\":{\"one_minute\":300,\"ten_minutes\":1500,\"one_hour\":2500,\"immediate\":true},\"default_blocking_response_code\":406,\"description\":\"Test NGWAF Workspace 6f8b9b15208f9286b393654218eff8d3_3\",\"ip_anonymization\":\"hashed\",\"mode\":\"black\",\"name\":\"tf_6f8b9b15208f9286b393654218eff8d3_3\"}"
http.Response (HTTPError): 400 - Bad Request:

    Title:  The request does not validate or is improperly formed
    Detail: Unknown agent level
    data_source_fastly_ngwaf_workspaces_test.go:15: Step 1/1 error: Error running apply: exit status 1
        
        Error: 400 - Bad Request:
        
            Title:  The request does not validate or is improperly formed
            Detail: Unknown agent level
        
          with fastly_ngwaf_workspace.example_3,
          on terraform_plugin_test.tf line 30, in resource "fastly_ngwaf_workspace" "example_3":
          30: resource "fastly_ngwaf_workspace" "example_3" {
```

 All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull
Requests](https://github.com/fastly/go-fastly/pulls) for the same
update/change?

<!-- You can erase any parts of this template not applicable to your
Pull Request. -->

### New Feature Submissions:

* [ ] Does your submission pass tests?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why
you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### User Impact

* [ ] What is the user impact of this change?

### Are there any considerations that need to be addressed for release?

<!-- Any breaking changes, etc -->